fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
imports_granularity = "Crate"
overflow_delimited_expr = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
wrap_comments = true